### ISSUE TITLE
`neverAccessedVariables`: regression with write-only variables

### ISSUE THREAD

**Issue by Gusarich** [nowarp/misti#101]
**Summary**
Unnecessary variables that aren't ever accessed apart from its own modifications

**Context**

**Examples**

```tact
let i: Int = 0;
repeat (n) {
    // some statements without the usage of `i` variable
    i += 1;
}
// `i` is not accessed afterward either
```

Use instead:

```tact
repeat (n) {
    // these statements without `i`
}
```

**Comment by jubnzv** [comment]
Thanks for reporting this. Actually, that's false negative.

These cases  [should be reported](https://github.com/nowarp/misti/blob/bdfd7b385f6bb15aaee1001871d8ec6017883d88/src/detectors/builtin/neverAccessedVariables.ts#L328) by `neverAccessedVariables` as a write-only variable. I missed the regression that the analyzer doesn't generate correct output for [this test](https://github.com/nowarp/misti/blob/bdfd7b385f6bb15aaee1001871d8ec6017883d88/test/good/never-accessed-1.tact#L3).
