### ISSUE TITLE
Could not find stdlib.tact

### ISSUE THREAD

**Issue by emochka2007** [nowarp/misti#102]
### Description
When attempting to use `misti` to run from `contracts/tactConfig.json`, a compilation error is encountered

### Current Behavior
Running the command `npx misti contracts/tactConfig.json` results in the following error:
``` bash
Compilation error: Could not find stdlib.tact at 
/node_modules/@nowarp/misti/node_modules/@tact-lang/compiler/stdlib/stdlib.tact
```

### `tactConfig.json`
```json
{
  "projects": [
    {
      "name": "Staking",
      "path": "./staking.tact",
      "output": "./build",
      "options": {}
    }
  ]
}
```

**Comment by jubnzv** [comment]
@emochka2007 Which version of misti are you using? Could you try installing the latest one, version 0.2.2, from npm?
