### ISSUE TITLE
Misti needs logo

### ISSUE THREAD

**Issue by anton-trunov** [nowarp/misti#104]
For instance, when integrated to the Web IDE, this logo can then be used for the Misti button (see https://github.com/nujan-io/nujan-ide/issues/92).

**Comment by novusnota** [comment]
Just wanted to open the similar issue :)
I'd like to iterate on it, have some ideas worth trying

**Comment by jubnzv** [comment]
![misti-transparent](https://github.com/user-attachments/assets/d09fa612-621c-4b2e-98a9-18f952127417)

Let's start with this one. The blue color palette resembles TON colors, the mountains reflect the name's origin, and the shield is related to security.

We can always change it if we have a better option.
