### ISSUE TITLE
Document which detectors are not available (if any) when Souffle is not installed

### ISSUE THREAD

**Issue by anton-trunov** [nowarp/misti#109]
A follow-up on issue #45

**Comment by jubnzv** [comment]
It prints the list of disabled detectors to the user: https://github.com/nowarp/misti/commit/65a77daa7a3e175597137a29e65dc69cca5ac7a4#diff-bda213326e78e9028995e292a6a51a3fa201bce4a8dd750adad751ee572e4924R131, including custom Souffle-based detectors. The expected action from the user is to either install Souffle or manually disable these detectors in the config file.

**Comment by anton-trunov** [comment]
looks good, thanks! Still would also be great to have this info in the docs. Can this be auto-generated?

**Comment by jubnzv** [comment]
https://nowarp.io/tools/misti/docs/next/detectors
