### ISSUE TITLE
Does single-file mode use `--all-detectors`?

### ISSUE THREAD

**Issue by anton-trunov** [nowarp/misti#112]
If I run `mist file.tact`, does it activate all the detectors?

If it does, it would be nice to document it in the `misti --help` command.

**Comment by jubnzv** [comment]
> If I run mist file.tact, does it activate all the detectors?

No, it doesn't. You can inspect the enabled detectors when running misti with `--verbose`.

**Comment by jubnzv** [comment]
Currently, the documentation has the list of detectors enabled by default: https://nowarp.io/tools/misti/docs/detectors
