### ISSUE TITLE
Soufflé: Declarative API

### ISSUE THREAD

**Issue by byakuren-hijiri** [nowarp/misti#12]
It is possible to implement a declarative API that operates of the created Soufflé entities in lambda functions like:
```typescript
const souffle = souffle(projectName, (s) => {
  const varUse = g.relation('varUse', ['var', 'func']);
  const varDecl = g.relation('varDecl', ['var', 'func']);
  const readOnly = g.relation('readOnly', ['var', 'func'], { io: "output" });
  const readOnlyRule1 = g.rule(
    readOnly,
    { relation: varDecl },
    { relation: varUse, negated: true }
  );
});
```

Which effectively describes the following Datalog rule and the relations in use:
```
readOnly(var, func) :-
    varDecl(var, func),
    !varUse(var, func),
```

**Comment by jubnzv** [comment]
It would be quite inconvenient to use, because facts and relations are connected to each other. It is much easier to write functions that construct AST within the given context as it implemented here: https://github.com/nowarp/misti/pull/120
