### ISSUE TITLE
Cell Overflow

### ISSUE THREAD

**Issue by anton-trunov** [nowarp/misti#20]
For instance, for cases like this one (the user tries to fit 5 refs into one cell):
```
beginCell()
  .storeRef(...)
  .storeAddress(myAddress())
  .storeRef(...)
  ...
  .storeRef(...)
  .storeRef(...)
  .storeRef(...)
.endCell()
```

Of course, this should work for the cell data as well.

**Comment by Gusarich** [comment]
It'll be easy to add the same thing for cell underflow detection on slice reads (for example, if you try to read 4 addresses from a slice). But it's very unlikely to occur in code without a similar problem with overflow.

**Comment by jubnzv** [comment]
It seems that the implementation should be split into two detectors: CellOverflow and CellUnderflow.

The reason for this is that these detectors are different. Both require dataflow analysis, but for the overflow detector, we are interested in tracking `Builder` operations, while for the underflow detector, we are focused on `Slice`, struct, and message types and their usage.

Thus, it will be more clear if we have two detectors.
