### ISSUE TITLE
Suppress warnings in comments

### ISSUE THREAD

**Issue by byakuren-hijiri** [nowarp/misti#43]
We would like to have something like this:
```
// @misti-suppress DivideBeforeMultiply
let a = (a / MAX_VAL) * 3;
```

To implement warning suppressions in the source code, such as in comments, it would be nice to have these in the syntax tree. This should be done in the compiler first.

**Comment by jubnzv** [comment]
One option for how it could be implemented without comments in the CST is to parse the line above the warning shown in the warning message:
```
[INFO] AsmIsUsed: asm function is used
test/detectors/AsmIsUsed.tact:2:1:
  1 | // @misti-suppress AsmIsUsed
> 2 | asm(-> 1 0) extends mutates fun loadRefEx(self: Slice): Cell { LDREF }
      ^
  3 |
Help: Using TVM assembly is a potentially dangerous operation that requires additional review
See: https://nowarp.io/tools/misti/docs/detectors/AsmIsUsed
```
