### ISSUE TITLE
Simplify Misti installation

### ISSUE THREAD

**Issue by byakuren-hijiri** [nowarp/misti#44]
Currently, Misti is distributed in the same way as the [Tact compiler](https://github.com/tact-lang/tact?tab=readme-ov-file#installation): it should be added to the contracts project via npm/yarn. However, it might be more convenient to have a separate bundle package distributed within the repository, especially when FunC support is implemented.

Node.js [provides](https://nodejs.org/api/single-executable-applications.html) a native way to bundle single-executable binaries since version 21. The [ncc](https://github.com/vercel/ncc) tool offers a wrapper to create a bundle using a single command. We can leverage that functionality, create bundles, sign them, and distribute them via GitHub releases.

**Comment by jubnzv** [comment]
It should be installed globally, e.g., using `npm install -g @nowarp/misti`, and should be available for all projects. The only thing that needs to be considered is the Tact stdlib. It can be safely distributed with Misti itself, as it follows Tact minor releases, and updating it should not be a problem.

**Comment by jubnzv** [comment]
It is already installable with `npm install -g`.
