### ISSUE TITLE
Detect entry points in single-contract mode

### ISSUE THREAD

**Issue by byakuren-hijiri** [nowarp/misti#57]
Single contract mode allows to execute Misti by specifying a single tact contract as an argument. Then, it creates a project with a dummy config in the temporary directory.

The problem is that this approach doesn't support relative imports; i.e. it doesn't copy imported files to the temporary directory.

**Comment by jubnzv** [comment]
This involves writing an import resolution logic to detect possible entry points of the project.

Related: #60
