### ISSUE TITLE
Usage of constant addresses

### ISSUE THREAD

**Issue by Gusarich** [nowarp/misti#77]
**Summary**
Similar to https://nowarp.github.io/tools/misti/docs/detectors/ZeroAddress, but more general.
Usage of something like `address("EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c")` would not be detected currently, but it's as bad as the usage of zero address in some contexts.

This also should apply for `newAddress` function.

I don't think it makes sense to provide more context or examples, since these would be same as for ZeroAddress.

**Comment by jubnzv** [comment]
Agreed, thank you. We could generalize the `zeroAddress` detector creating another kind of warnings. I suggest making it optional or low severity, since it might be valid to e.g. initialize a contract with a hard-coded address.

**Comment by Gusarich** [comment]
@jubnzv Misti doesn't seem to report anything for this code:
```tact
contract Test {
    receive() {
        address("0QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACkT"); // constant address
    }
}
```

**Comment by jubnzv** [comment]
@Gusarich This detector is disabled by default. You should run the analyzer with the `--all-detectors` CLI option. Or create [a configuration file](https://nowarp.github.io/tools/misti/docs/next/tutorial/configuration) that includes the `constantAddress` detector.
