### ISSUE TITLE
Generic Soufflé detector

### ISSUE THREAD

**Issue by byakuren-hijiri** [nowarp/misti#8]
It is possible to add a "generic" Soufflé detector to enable users to create a new detector without writing extra TypeScript code.

The idea is to create a library of constraint generators which provides API to create pre-defined Soufflé facts. For example, such a library might contains constraint generators from the `readOnlyVariables` detector that adds facts `varUse`, `varAssign` and `varDecl` to a any detector if requested.

Having this kind of a library, the user can implement a new detector in two steps:
1. Define a small configuration in TypeScript that loads the required constraint generators.
2. Add a custom Soufflé rule using the bindings library.

After that, they can simply run a new detector without any interaction with IR in their code.

Here is an example:
```typescript
export class TestDetector extends CustomSouffleDetector {
  // Load the required constraint generators
  constructor() {
    this.loadConstraints("varDecl", "varUse", "varAssign");
  }

  // Add custom Soufflé rules that uses the facts generated by constraints
  addCustomRules(program: SouffleProgram) {
     // readOnly(var, func) :-
     //   varDecl(var, func),
     //   varAssign(var, func),
     //   !varUse(var, func).
     let rule = SouffleRule("readOnly", "var", "func");
     rule.addCondition("varDecl", "var", "func");
     rule.addCondition("varAssign", "var", "func");
     rule.addCondition("!varUse", "var", "func");
     program.addRule(rule)
  }
}

**Comment by jubnzv** [comment]
This could be implemented later when developing new detectors. Actually, it will be a kind of refactoring performed when adding the same functionality to new detectors.
