### ISSUE TITLE
`SendParameters` Sanity Checker

### ISSUE THREAD

**Issue by jubnzv** [nowarp/misti#85]
**Summary**
Check dangerous patterns in the `mode` field of [`SendParameters`](https://docs.tact-lang.org/book/send).

**Context**
https://github.com/tact-lang/tact/issues/180

**Examples**

```tact
SendParameters{
    ...
    mode: SendRemainingValue + SendRemainingValue, 
    ...
}
```

Should raise a warning:
* flags in the mode field should be used at most one time;
* the mode expression should only contain the + sign;
* TODO: check if some combinations of flags are meaningless;
* integer literals should not be used, only symbolic constants.

**Comment by jubnzv** [comment]
Additional idea: maybe we could leverage the Tact interpreter to reason about possible problems of `mode` values (depends on #70)

**Comment by Gusarich** [comment]
> * the mode expression should only contain the + sign;

actually it's recommended to use the binary or `|` operator instead of `+`
