### ISSUE TITLE
Detect eta-like simplifications

### ISSUE THREAD

**Issue by anton-trunov** [nowarp/misti#92]
**Summary**

Things that can be simplified using eta-rules (eta-conversion in type theory):
- booleans: `cond ? true : false` -> `cond`, for any boolean expression `cond`, or 
- structs: `Foo {x: ex, y: ey}.x` -> `ex`, for any expression `ex`.

are most likely produced either by an inexperienced programmer or result from a typo or other form of mistake.

This also can be applied to statements as well, see the example below.

**Context**

I don't think it's a high-priority detector, although I've seen code like this (especially in the example below) in the wild.

**Examples**

```tact
fun foo(x : Int): Bool {
  // ... some logic here
  if (condition) {
    return true;
  } else {
    return false;
  }
}
```

Use instead:

```tact
fun foo(x : Int): Bool {
  // ... some logic here
  return condition;
}
```

One more example with `==` for booleans:

```tact
fun foo(x : Int): Bool {
  require(boolean_expression == true, "Error message");
}
```

Use instead:

```tact
fun foo(x : Int): Bool {
  require(boolean_expression, "Error message");
}
```

**Comment by jubnzv** [comment]
This requires some improvements in the constant evaluator, right? I haven't found an issue, though.

**Comment by anton-trunov** [comment]
No, no, the constant evaluator would simplify away those cases (at least for expression), but misti could detect things like that and issue a warning
