### ISSUE TITLE
Allow execution without tact project config

### ISSUE THREAD

**Issue by Gusarich** [nowarp/misti#94]
Blueprint projects don't have tact project config in them by default and I have to either define it myself or just call Misti on each of the contract files separately. Would be nice to have the ability to just specify some root directory so that misti recursively finds .tact sources in it and calls them in a single-file mode.

**Comment by jubnzv** [comment]
Agreed.

We need #57 to be implemented first. It requires writing some functionality to handle import graph in the compiler.

**Comment by jubnzv** [comment]
https://github.com/nowarp/blueprint-misti will be more usable after introducing this feature.

**Comment by novusnota** [comment]
Or we could just demand Blueprint to use `tact.config.json` like any other Tact-related tool, which would simplify Blueprint's internal structure AND alleviate this problem altogether

**Comment by jubnzv** [comment]
Supported in `blueprint-misti`: https://github.com/nowarp/blueprint-misti/pull/7.

Running `yarn blueprint misti` without options opens the interactive menu which enables user to choose a project to analyze:

![pic](https://github.com/user-attachments/assets/38e1fed5-ebfb-4cb5-8953-beac279e6a28)
